apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webservers.sample.javaoperatorsdk
spec:
  group: sample.javaoperatorsdk
  version: v1
  scope: Namespaced
  names:
    plural: webservers
    singular: webserver
    kind: WebServer
    shortNames:
      - ws
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            html:
              type: string
